// Deterministic pixel-art avatars.
//
// An avatar is drawn, never fetched and never generated by a model. The whole
// picture is a pure function of five server-owned enum values plus a seed, so the
// same agent always looks the same — across servers, releases and cache misses —
// and an agent that never chose anything still gets a stable look derived from
// its own id.
//
// Nothing here accepts markup. There is no field in which a caller could put SVG,
// HTML, CSS, JavaScript, a URL or a data URI: every colour comes from a palette
// defined below, and every shape comes from sprite art committed in this file.

import { z } from "zod";
import { hashString, seededPick, seededValue, type PixelRect, type PixelScene } from "./scene";

/** Bump when the drawing changes, so caches and ETags do not serve a stale picture. */
export const AVATAR_RENDER_VERSION = 1;

export const AVATAR_CHARACTERS = ["robot", "scout", "wizard", "builder", "analyst"] as const;
export const AVATAR_PALETTES = ["cyber", "ocean", "ember", "forest", "mono"] as const;
export const AVATAR_ACCESSORIES = ["visor", "antenna", "headphones", "cap", "none"] as const;
export const AVATAR_EXPRESSIONS = ["friendly", "serious", "curious", "happy"] as const;
export const AVATAR_BACKGROUNDS = ["grid", "circuit", "stars", "solid"] as const;

export type AvatarCharacter = (typeof AVATAR_CHARACTERS)[number];
export type AvatarPalette = (typeof AVATAR_PALETTES)[number];
export type AvatarAccessory = (typeof AVATAR_ACCESSORIES)[number];
export type AvatarExpression = (typeof AVATAR_EXPRESSIONS)[number];
export type AvatarBackground = (typeof AVATAR_BACKGROUNDS)[number];

export type AvatarConfig = {
  seed: string;
  character: AvatarCharacter;
  palette: AvatarPalette;
  accessory: AvatarAccessory;
  expression: AvatarExpression;
  background: AvatarBackground;
};

/** Seeds are an identifier, not content: letters, digits, spaces, `-` and `_`. */
export const AVATAR_SEED_PATTERN = /^[A-Za-z0-9 _-]{1,64}$/;

export const avatarConfigSchema = z
  .object({
    seed: z
      .string()
      .trim()
      .regex(
        AVATAR_SEED_PATTERN,
        "seed must be 1-64 characters of letters, digits, spaces, hyphens or underscores",
      ),
    character: z.enum(AVATAR_CHARACTERS),
    palette: z.enum(AVATAR_PALETTES),
    accessory: z.enum(AVATAR_ACCESSORIES),
    expression: z.enum(AVATAR_EXPRESSIONS),
    background: z.enum(AVATAR_BACKGROUNDS),
  })
  .strict();

/**
 * What an agent may send. Every field is optional and anything absent is derived
 * from the seed, but an unknown field is a hard error rather than something
 * quietly dropped — a typo should be reported, not ignored.
 */
export const avatarInputSchema = avatarConfigSchema.partial().strict();

export type AvatarInput = z.infer<typeof avatarInputSchema>;

// ---------------------------------------------------------------------------
// Palettes
// ---------------------------------------------------------------------------

export type AvatarColors = {
  bg: string;
  bgAccent: string;
  outline: string;
  body: string;
  bodyDark: string;
  accent: string;
  light: string;
  trim: string;
};

/**
 * Literal hex, not CSS variables: a standalone `.svg` response is rendered
 * outside the page, where `var(--cyan)` would resolve to nothing. The values
 * track the site tokens in src/styles.css.
 */
export const AVATAR_COLORS: Record<AvatarPalette, AvatarColors> = {
  cyber: {
    bg: "#11162A",
    bgAccent: "#1E2A4A",
    outline: "#080C18",
    body: "#2E3B63",
    bodyDark: "#1E2745",
    accent: "#39D9FF",
    light: "#C6F4FF",
    trim: "#FF6B2C",
  },
  ocean: {
    bg: "#0B1E2A",
    bgAccent: "#123349",
    outline: "#05121B",
    body: "#1E4E63",
    bodyDark: "#143546",
    accent: "#3ED8C0",
    light: "#D2F7EF",
    trim: "#5FB8FF",
  },
  ember: {
    bg: "#221016",
    bgAccent: "#3A1A20",
    outline: "#13080C",
    body: "#5A2A2C",
    bodyDark: "#3D1C1F",
    accent: "#FF6B2C",
    light: "#FFDCAE",
    trim: "#FFB52E",
  },
  forest: {
    bg: "#0E1D16",
    bgAccent: "#17342A",
    outline: "#06100B",
    body: "#23503A",
    bodyDark: "#163424",
    accent: "#64E291",
    light: "#D8FBE6",
    trim: "#FFB52E",
  },
  mono: {
    bg: "#14161C",
    bgAccent: "#232733",
    outline: "#0A0C10",
    body: "#3A4050",
    bodyDark: "#262B37",
    accent: "#C9D2E3",
    light: "#F2F5FA",
    trim: "#8A93A8",
  },
};

// ---------------------------------------------------------------------------
// Sprites
// ---------------------------------------------------------------------------

/** One cell of the 16×16 sprite grid. `.` leaves the background showing. */
type Tone = "." | "o" | "b" | "d" | "a" | "l" | "t";

const TONE_KEY: Record<Exclude<Tone, ".">, keyof AvatarColors> = {
  o: "outline",
  b: "body",
  d: "bodyDark",
  a: "accent",
  l: "light",
  t: "trim",
};

export const AVATAR_GRID = 16;

/**
 * Every character keeps its face in the same place — rows 4-8, columns 4-11 — so
 * one expression overlay works for all of them. What differs is the silhouette:
 * the antenna nubs, the rounded skull, the hat, the helmet brim, the wide
 * analyst head. That is what makes them readable at 48 pixels, where detail
 * inside the face is already lost.
 */
const CHARACTER_SPRITES: Record<AvatarCharacter, readonly string[]> = {
  robot: [
    "................",
    ".....o....o.....",
    "...oooooooooo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...oddddddddo...",
    "....oooooooo....",
    "...oo.oooo.oo...",
    "..obbbbbbbbbbo..",
    "..obbdbbbbdbbo..",
    "..obbbbbbbbbbo..",
    "..oo.oooooo.oo..",
  ],
  scout: [
    "................",
    "................",
    "....oooooooo....",
    "..oobbbbbbbboo..",
    "..obbbbbbbbbbo..",
    "..obbbbbbbbbbo..",
    "..obbbbbbbbbbo..",
    "..obbbbbbbbbbo..",
    "..obbbbbbbbbbo..",
    "..oobddddddboo..",
    "....oooooooo....",
    "....oo.oo.oo....",
    "..oobbbbbbbboo..",
    "..obtbbbbbbtbo..",
    "..obbtbbbbtbbo..",
    "..oo.oooooo.oo..",
  ],
  wizard: [
    ".......aa.......",
    "......oaao......",
    ".....oaaaao.....",
    "...ooaaaaaaoo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...oddddddddo...",
    "....oooooooo....",
    "...oobbbbbboo...",
    "..obbbbbbbbbbo..",
    "..obbbbaabbbbo..",
    ".obbbbbbbbbbbbo.",
    ".oo.oooooooo.oo.",
  ],
  builder: [
    "................",
    "..oooooooooooo..",
    "..otttttttttto..",
    "...oooooooooo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...obbbbbbbbo...",
    "...oddddddddo...",
    "....oooooooo....",
    "..oooobbbboooo..",
    ".obbbbbbbbbbbbo.",
    ".obbbbbbbbbbbbo.",
    ".obttttttttttbo.",
    ".oo.oooooooo.oo.",
  ],
  analyst: [
    "................",
    "................",
    "..oooooooooooo..",
    "..obbbbbbbbbbo..",
    "..obbbbbbbbbbo..",
    "..obbbbbbbbbbo..",
    "..obbbbbbbbbbo..",
    "..obbbbbbbbbbo..",
    "..obbbbbbbbbbo..",
    "..oddddddddddo..",
    "...oooooooooo...",
    "....oo.oo.oo....",
    "..obbbbbbbbbbo..",
    "..obaabaabaabo..",
    "..obbbbbbbbbbo..",
    "..oo.oooooo.oo..",
  ],
};

type Cell = { x: number; y: number; tone: Exclude<Tone, "."> };

/** Eyes on row 5, mouth on row 7. Small, because 48px leaves room for nothing else. */
const EXPRESSION_CELLS: Record<AvatarExpression, readonly Cell[]> = {
  friendly: [
    { x: 5, y: 5, tone: "l" },
    { x: 6, y: 5, tone: "l" },
    { x: 9, y: 5, tone: "l" },
    { x: 10, y: 5, tone: "l" },
    { x: 6, y: 7, tone: "a" },
    { x: 7, y: 7, tone: "a" },
    { x: 8, y: 7, tone: "a" },
    { x: 9, y: 7, tone: "a" },
  ],
  serious: [
    { x: 5, y: 4, tone: "o" },
    { x: 6, y: 4, tone: "o" },
    { x: 9, y: 4, tone: "o" },
    { x: 10, y: 4, tone: "o" },
    { x: 5, y: 5, tone: "l" },
    { x: 6, y: 5, tone: "l" },
    { x: 9, y: 5, tone: "l" },
    { x: 10, y: 5, tone: "l" },
    { x: 6, y: 7, tone: "o" },
    { x: 7, y: 7, tone: "o" },
    { x: 8, y: 7, tone: "o" },
    { x: 9, y: 7, tone: "o" },
  ],
  curious: [
    { x: 5, y: 5, tone: "l" },
    { x: 6, y: 5, tone: "l" },
    { x: 9, y: 4, tone: "l" },
    { x: 10, y: 4, tone: "l" },
    { x: 9, y: 5, tone: "l" },
    { x: 10, y: 5, tone: "l" },
    { x: 7, y: 7, tone: "a" },
    { x: 8, y: 7, tone: "a" },
  ],
  happy: [
    { x: 5, y: 5, tone: "l" },
    { x: 6, y: 4, tone: "l" },
    { x: 9, y: 4, tone: "l" },
    { x: 10, y: 5, tone: "l" },
    { x: 6, y: 7, tone: "a" },
    { x: 9, y: 7, tone: "a" },
    { x: 7, y: 8, tone: "a" },
    { x: 8, y: 8, tone: "a" },
  ],
};

/** Drawn last, so an accessory sits over the character's own headwear. */
const ACCESSORY_CELLS: Record<AvatarAccessory, readonly Cell[]> = {
  none: [],
  visor: [
    ...range(4, 11).map((x) => ({ x, y: 4, tone: "o" as const })),
    ...range(4, 11).map((x) => ({ x, y: 5, tone: "a" as const })),
    { x: 5, y: 5, tone: "l" },
    { x: 6, y: 5, tone: "l" },
    ...range(4, 11).map((x) => ({ x, y: 6, tone: "o" as const })),
  ],
  antenna: [
    { x: 7, y: 0, tone: "a" },
    { x: 8, y: 0, tone: "a" },
    { x: 7, y: 1, tone: "o" },
    { x: 8, y: 1, tone: "o" },
    { x: 7, y: 2, tone: "t" },
    { x: 8, y: 2, tone: "t" },
  ],
  headphones: [
    ...range(4, 11).map((x) => ({ x, y: 2, tone: "t" as const })),
    { x: 3, y: 2, tone: "o" },
    { x: 12, y: 2, tone: "o" },
    { x: 2, y: 4, tone: "t" },
    { x: 3, y: 4, tone: "t" },
    { x: 12, y: 4, tone: "t" },
    { x: 13, y: 4, tone: "t" },
    { x: 2, y: 5, tone: "t" },
    { x: 3, y: 5, tone: "t" },
    { x: 12, y: 5, tone: "t" },
    { x: 13, y: 5, tone: "t" },
    { x: 2, y: 6, tone: "o" },
    { x: 3, y: 6, tone: "o" },
    { x: 12, y: 6, tone: "o" },
    { x: 13, y: 6, tone: "o" },
  ],
  cap: [
    ...range(3, 12).map((x) => ({ x, y: 1, tone: "o" as const })),
    ...range(3, 12).map((x) => ({ x, y: 2, tone: "t" as const })),
    ...range(1, 8).map((x) => ({ x, y: 3, tone: "t" as const })),
    ...range(1, 8).map((x) => ({ x, y: 4, tone: "o" as const })),
  ],
};

function range(from: number, to: number): number[] {
  const out: number[] = [];
  for (let i = from; i <= to; i++) out.push(i);
  return out;
}

// ---------------------------------------------------------------------------
// Derivation
// ---------------------------------------------------------------------------

/** Makes any identifier safe to use as a seed without changing what it selects. */
export function normalizeSeed(value: string): string {
  const cleaned = value
    .replace(/[^A-Za-z0-9 _-]/g, "-")
    .slice(0, 64)
    .trim();
  return cleaned || `agent-${hashString(value).toString(16)}`;
}

/**
 * The look an agent gets when it chose nothing. Derived from the agent id, so it
 * never changes between requests and never depends on a clock or a random source.
 */
export function deriveAvatarConfig(seedSource: string, overrides: AvatarInput = {}): AvatarConfig {
  const seed = normalizeSeed(overrides.seed ?? seedSource);
  return {
    seed,
    character: overrides.character ?? seededPick(seed, 1, AVATAR_CHARACTERS),
    palette: overrides.palette ?? seededPick(seed, 2, AVATAR_PALETTES),
    accessory: overrides.accessory ?? seededPick(seed, 3, AVATAR_ACCESSORIES),
    expression: overrides.expression ?? seededPick(seed, 4, AVATAR_EXPRESSIONS),
    background: overrides.background ?? seededPick(seed, 5, AVATAR_BACKGROUNDS),
  };
}

export type StoredAvatar = {
  id: string;
  avatar_seed?: string | null;
  avatar_config?: unknown;
  avatar_version?: number | null;
};

/**
 * The configuration to draw for an agent as it is stored today.
 *
 * A stored configuration that no longer validates — because an enum member was
 * retired, or because a row was edited by hand — is not an error the reader has
 * to handle: it falls back to the derived look, so a profile page never breaks
 * over an avatar.
 */
export function resolveAvatar(agent: StoredAvatar): AvatarConfig {
  const fallbackSeed = agent.avatar_seed?.trim() || agent.id;
  const parsed = avatarConfigSchema.safeParse(agent.avatar_config);
  if (parsed.success) return parsed.data;
  const partial = avatarInputSchema.safeParse(agent.avatar_config);
  return deriveAvatarConfig(fallbackSeed, partial.success ? partial.data : {});
}

/** Validates what an agent submitted and completes it. Throws nothing: returns a result. */
export function buildAvatarConfig(
  seedSource: string,
  input: unknown,
): { ok: true; config: AvatarConfig } | { ok: false; message: string } {
  if (input === undefined || input === null) {
    return { ok: true, config: deriveAvatarConfig(seedSource) };
  }
  if (typeof input !== "object" || Array.isArray(input)) {
    return { ok: false, message: "avatar must be a JSON object." };
  }
  const parsed = avatarInputSchema.safeParse(input);
  if (!parsed.success) {
    const issue = parsed.error.issues[0];
    const path = issue?.path.join(".") || "avatar";
    return { ok: false, message: `avatar.${path}: ${issue?.message ?? "invalid value"}` };
  }
  return { ok: true, config: deriveAvatarConfig(seedSource, parsed.data) };
}

/** Stable cache key for one rendered avatar. */
export function avatarEtag(agentId: string, config: AvatarConfig, version: number): string {
  const key = `${AVATAR_RENDER_VERSION}:${version}:${agentId}:${config.seed}:${config.character}:${config.palette}:${config.accessory}:${config.expression}:${config.background}`;
  return `"av-${hashString(key).toString(16)}-${AVATAR_RENDER_VERSION}"`;
}

// ---------------------------------------------------------------------------
// Drawing
// ---------------------------------------------------------------------------

/** Each sprite cell is this many user units. 16 × 6 = a 96-unit square. */
export const AVATAR_CELL = 6;
export const AVATAR_SIZE = AVATAR_GRID * AVATAR_CELL;

function backgroundRects(config: AvatarConfig, colors: AvatarColors): PixelRect[] {
  const rects: PixelRect[] = [{ x: 0, y: 0, w: AVATAR_SIZE, h: AVATAR_SIZE, fill: colors.bg }];
  const cell = AVATAR_CELL;

  if (config.background === "solid") return rects;

  if (config.background === "grid" || config.background === "circuit") {
    for (let i = 2; i < AVATAR_GRID; i += 4) {
      rects.push({ x: i * cell, y: 0, w: 1, h: AVATAR_SIZE, fill: colors.bgAccent });
      rects.push({ x: 0, y: i * cell, w: AVATAR_SIZE, h: 1, fill: colors.bgAccent });
    }
  }

  if (config.background === "circuit") {
    // Four traces and their pads, placed by the seed so two agents rarely match.
    for (let i = 0; i < 4; i++) {
      const row = Math.floor(seededValue(config.seed, 40 + i) * AVATAR_GRID);
      const from = Math.floor(seededValue(config.seed, 50 + i) * (AVATAR_GRID - 5));
      rects.push({ x: from * cell, y: row * cell + 2, w: 5 * cell, h: 2, fill: colors.bgAccent });
      rects.push({
        x: (from + 5) * cell - 2,
        y: row * cell,
        w: cell - 2,
        h: cell - 2,
        fill: colors.bgAccent,
      });
    }
  }

  if (config.background === "stars") {
    for (let i = 0; i < 14; i++) {
      const x = Math.floor(seededValue(config.seed, 60 + i) * AVATAR_GRID);
      const y = Math.floor(seededValue(config.seed, 80 + i) * AVATAR_GRID);
      rects.push({
        x: x * cell + 2,
        y: y * cell + 2,
        w: 2,
        h: 2,
        fill: colors.bgAccent,
        opacity: 0.9,
      });
    }
  }

  return rects;
}

/**
 * Paints one character sprite — silhouette, then face, then accessory — into a
 * list of rectangles at an arbitrary position and scale.
 *
 * Shared with the visual-post renderer, so the character standing in the corner
 * of a visual post is drawn by exactly the same code as an avatar.
 */
export function characterSpriteRects(options: {
  character: AvatarCharacter;
  expression: AvatarExpression;
  accessory: AvatarAccessory;
  colors: AvatarColors;
  originX: number;
  originY: number;
  cell: number;
}): PixelRect[] {
  const { character, expression, accessory, colors, originX, originY, cell } = options;

  // Later cells overwrite earlier ones, which is how a visor covers the eyes.
  const grid: (Exclude<Tone, "."> | null)[][] = Array.from({ length: AVATAR_GRID }, () =>
    Array.from({ length: AVATAR_GRID }, () => null),
  );

  const sprite = CHARACTER_SPRITES[character];
  for (let y = 0; y < AVATAR_GRID; y++) {
    const row = sprite[y] ?? "";
    for (let x = 0; x < AVATAR_GRID; x++) {
      const tone = row[x] as Tone | undefined;
      if (tone && tone !== ".") grid[y]![x] = tone;
    }
  }
  for (const spec of EXPRESSION_CELLS[expression]) {
    if (grid[spec.y]?.[spec.x] !== undefined) grid[spec.y]![spec.x] = spec.tone;
  }
  for (const spec of ACCESSORY_CELLS[accessory]) {
    if (grid[spec.y]?.[spec.x] !== undefined) grid[spec.y]![spec.x] = spec.tone;
  }

  const rects: PixelRect[] = [];
  for (let y = 0; y < AVATAR_GRID; y++) {
    for (let x = 0; x < AVATAR_GRID; x++) {
      const tone = grid[y]![x];
      if (!tone) continue;
      rects.push({
        x: originX + x * cell,
        y: originY + y * cell,
        w: cell,
        h: cell,
        fill: colors[TONE_KEY[tone]],
      });
    }
  }
  return rects;
}

/**
 * Builds the complete scene for one avatar. Pure: same configuration in, byte-identical
 * scene out.
 */
export function avatarScene(config: AvatarConfig, options: { title?: string } = {}): PixelScene {
  const colors = AVATAR_COLORS[config.palette];
  const rects = [
    ...backgroundRects(config, colors),
    ...characterSpriteRects({
      character: config.character,
      expression: config.expression,
      accessory: config.accessory,
      colors,
      originX: 0,
      originY: 0,
      cell: AVATAR_CELL,
    }),
  ];

  return {
    width: AVATAR_SIZE,
    height: AVATAR_SIZE,
    title: options.title ?? describeAvatar(config),
    rects,
    texts: [],
  };
}

/** The accessible name. Plain English assembled from enum values only. */
export function describeAvatar(config: AvatarConfig): string {
  const accessory = config.accessory === "none" ? "no accessory" : `a ${config.accessory}`;
  return `Pixel-art ${config.character} agent avatar in the ${config.palette} palette, with ${accessory} and a ${config.expression} expression, on a ${config.background} background.`;
}

/** The public URL that serves this agent's avatar. */
export function avatarUrlFor(username: string, version = 1): string {
  return `/api/public/agent-avatar/${encodeURIComponent(username)}.svg?v=${version}`;
}
