/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectAgentRouteImport } from './routes/connect-agent'
import { Route as FeedRouteImport } from './routes/feed'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as AdminDemoAgentsRouteImport } from './routes/admin.demo-agents'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminVisualPostsRouteImport } from './routes/admin.visual-posts'
import { Route as AgentDashboardIndexRouteImport } from './routes/agent-dashboard.index'
import { Route as AgentDashboardAccessRouteImport } from './routes/agent-dashboard.access'
import { Route as AgentsAgentIdRouteImport } from './routes/agents.$agentId'
import { Route as PostsPostIdRouteImport } from './routes/posts.$postId'
import { Route as AdminAgentsAgentIdRouteImport } from './routes/admin.agents.$agentId'
import { Route as AgentsAgentIdChatRouteImport } from './routes/agents.$agentId.chat'
import { Route as ApiCronRunDemoAgentRouteImport } from './routes/api/cron/run-demo-agent'
import { Route as ApiOwnerDashboardSplatRouteImport } from './routes/api/owner-dashboard.$'
import { Route as ApiPublicAgentRegisterRouteImport } from './routes/api/public/agent-register'
import { Route as ApiPublicAgentApiSplatRouteImport } from './routes/api/public/agent-api.$'
import { Route as ApiPublicAgentAvatarSplatRouteImport } from './routes/api/public/agent-avatar.$'
import { Route as ApiPublicConversationsSplatRouteImport } from './routes/api/public/conversations.$'
import { Route as ApiPublicPostVisualSplatRouteImport } from './routes/api/public/post-visual.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectAgentRoute = ConnectAgentRouteImport.update({
  id: '/connect-agent',
  path: '/connect-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedRoute = FeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/admin/conversations',
  path: '/admin/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDemoAgentsRoute = AdminDemoAgentsRouteImport.update({
  id: '/admin/demo-agents',
  path: '/admin/demo-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVisualPostsRoute = AdminVisualPostsRouteImport.update({
  id: '/admin/visual-posts',
  path: '/admin/visual-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardIndexRoute = AgentDashboardIndexRouteImport.update({
  id: '/agent-dashboard/',
  path: '/agent-dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentDashboardAccessRoute = AgentDashboardAccessRouteImport.update({
  id: '/agent-dashboard/access',
  path: '/agent-dashboard/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdRoute = AgentsAgentIdRouteImport.update({
  id: '/agents/$agentId',
  path: '/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsPostIdRoute = PostsPostIdRouteImport.update({
  id: '/posts/$postId',
  path: '/posts/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAgentsAgentIdRoute = AdminAgentsAgentIdRouteImport.update({
  id: '/admin/agents/$agentId',
  path: '/admin/agents/$agentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsAgentIdChatRoute = AgentsAgentIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AgentsAgentIdRoute,
} as any)
const ApiCronRunDemoAgentRoute = ApiCronRunDemoAgentRouteImport.update({
  id: '/api/cron/run-demo-agent',
  path: '/api/cron/run-demo-agent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOwnerDashboardSplatRoute = ApiOwnerDashboardSplatRouteImport.update({
  id: '/api/owner-dashboard/$',
  path: '/api/owner-dashboard/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentRegisterRoute = ApiPublicAgentRegisterRouteImport.update({
  id: '/api/public/agent-register',
  path: '/api/public/agent-register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentApiSplatRoute = ApiPublicAgentApiSplatRouteImport.update({
  id: '/api/public/agent-api/$',
  path: '/api/public/agent-api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgentAvatarSplatRoute =
  ApiPublicAgentAvatarSplatRouteImport.update({
    id: '/api/public/agent-avatar/$',
    path: '/api/public/agent-avatar/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicConversationsSplatRoute =
  ApiPublicConversationsSplatRouteImport.update({
    id: '/api/public/conversations/$',
    path: '/api/public/conversations/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPostVisualSplatRoute =
  ApiPublicPostVisualSplatRouteImport.update({
    id: '/api/public/post-visual/$',
    path: '/api/public/post-visual/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-agent': typeof ConnectAgentRoute
  '/feed': typeof FeedRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/demo-agents': typeof AdminDemoAgentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/visual-posts': typeof AdminVisualPostsRoute
  '/agent-dashboard/access': typeof AgentDashboardAccessRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agent-dashboard/': typeof AgentDashboardIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/api/cron/run-demo-agent': typeof ApiCronRunDemoAgentRoute
  '/api/owner-dashboard/$': typeof ApiOwnerDashboardSplatRoute
  '/api/public/agent-register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent-api/$': typeof ApiPublicAgentApiSplatRoute
  '/api/public/agent-avatar/$': typeof ApiPublicAgentAvatarSplatRoute
  '/api/public/conversations/$': typeof ApiPublicConversationsSplatRoute
  '/api/public/post-visual/$': typeof ApiPublicPostVisualSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-agent': typeof ConnectAgentRoute
  '/feed': typeof FeedRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/demo-agents': typeof AdminDemoAgentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/visual-posts': typeof AdminVisualPostsRoute
  '/agent-dashboard/access': typeof AgentDashboardAccessRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin': typeof AdminIndexRoute
  '/agent-dashboard': typeof AgentDashboardIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/api/cron/run-demo-agent': typeof ApiCronRunDemoAgentRoute
  '/api/owner-dashboard/$': typeof ApiOwnerDashboardSplatRoute
  '/api/public/agent-register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent-api/$': typeof ApiPublicAgentApiSplatRoute
  '/api/public/agent-avatar/$': typeof ApiPublicAgentAvatarSplatRoute
  '/api/public/conversations/$': typeof ApiPublicConversationsSplatRoute
  '/api/public/post-visual/$': typeof ApiPublicPostVisualSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-agent': typeof ConnectAgentRoute
  '/feed': typeof FeedRoute
  '/admin/conversations': typeof AdminConversationsRoute
  '/admin/demo-agents': typeof AdminDemoAgentsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/visual-posts': typeof AdminVisualPostsRoute
  '/agent-dashboard/access': typeof AgentDashboardAccessRoute
  '/agents/$agentId': typeof AgentsAgentIdRouteWithChildren
  '/posts/$postId': typeof PostsPostIdRoute
  '/admin/': typeof AdminIndexRoute
  '/agent-dashboard/': typeof AgentDashboardIndexRoute
  '/admin/agents/$agentId': typeof AdminAgentsAgentIdRoute
  '/agents/$agentId/chat': typeof AgentsAgentIdChatRoute
  '/api/cron/run-demo-agent': typeof ApiCronRunDemoAgentRoute
  '/api/owner-dashboard/$': typeof ApiOwnerDashboardSplatRoute
  '/api/public/agent-register': typeof ApiPublicAgentRegisterRoute
  '/api/public/agent-api/$': typeof ApiPublicAgentApiSplatRoute
  '/api/public/agent-avatar/$': typeof ApiPublicAgentAvatarSplatRoute
  '/api/public/conversations/$': typeof ApiPublicConversationsSplatRoute
  '/api/public/post-visual/$': typeof ApiPublicPostVisualSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect-agent'
    | '/feed'
    | '/admin/conversations'
    | '/admin/demo-agents'
    | '/admin/login'
    | '/admin/visual-posts'
    | '/agent-dashboard/access'
    | '/agents/$agentId'
    | '/posts/$postId'
    | '/admin/'
    | '/agent-dashboard/'
    | '/admin/agents/$agentId'
    | '/agents/$agentId/chat'
    | '/api/cron/run-demo-agent'
    | '/api/owner-dashboard/$'
    | '/api/public/agent-register'
    | '/api/public/agent-api/$'
    | '/api/public/agent-avatar/$'
    | '/api/public/conversations/$'
    | '/api/public/post-visual/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect-agent'
    | '/feed'
    | '/admin/conversations'
    | '/admin/demo-agents'
    | '/admin/login'
    | '/admin/visual-posts'
    | '/agent-dashboard/access'
    | '/agents/$agentId'
    | '/posts/$postId'
    | '/admin'
    | '/agent-dashboard'
    | '/admin/agents/$agentId'
    | '/agents/$agentId/chat'
    | '/api/cron/run-demo-agent'
    | '/api/owner-dashboard/$'
    | '/api/public/agent-register'
    | '/api/public/agent-api/$'
    | '/api/public/agent-avatar/$'
    | '/api/public/conversations/$'
    | '/api/public/post-visual/$'
  id:
    | '__root__'
    | '/'
    | '/connect-agent'
    | '/feed'
    | '/admin/conversations'
    | '/admin/demo-agents'
    | '/admin/login'
    | '/admin/visual-posts'
    | '/agent-dashboard/access'
    | '/agents/$agentId'
    | '/posts/$postId'
    | '/admin/'
    | '/agent-dashboard/'
    | '/admin/agents/$agentId'
    | '/agents/$agentId/chat'
    | '/api/cron/run-demo-agent'
    | '/api/owner-dashboard/$'
    | '/api/public/agent-register'
    | '/api/public/agent-api/$'
    | '/api/public/agent-avatar/$'
    | '/api/public/conversations/$'
    | '/api/public/post-visual/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectAgentRoute: typeof ConnectAgentRoute
  FeedRoute: typeof FeedRoute
  AdminConversationsRoute: typeof AdminConversationsRoute
  AdminDemoAgentsRoute: typeof AdminDemoAgentsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminVisualPostsRoute: typeof AdminVisualPostsRoute
  AgentDashboardAccessRoute: typeof AgentDashboardAccessRoute
  AgentsAgentIdRoute: typeof AgentsAgentIdRouteWithChildren
  PostsPostIdRoute: typeof PostsPostIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AgentDashboardIndexRoute: typeof AgentDashboardIndexRoute
  AdminAgentsAgentIdRoute: typeof AdminAgentsAgentIdRoute
  ApiCronRunDemoAgentRoute: typeof ApiCronRunDemoAgentRoute
  ApiOwnerDashboardSplatRoute: typeof ApiOwnerDashboardSplatRoute
  ApiPublicAgentRegisterRoute: typeof ApiPublicAgentRegisterRoute
  ApiPublicAgentApiSplatRoute: typeof ApiPublicAgentApiSplatRoute
  ApiPublicAgentAvatarSplatRoute: typeof ApiPublicAgentAvatarSplatRoute
  ApiPublicConversationsSplatRoute: typeof ApiPublicConversationsSplatRoute
  ApiPublicPostVisualSplatRoute: typeof ApiPublicPostVisualSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-agent': {
      id: '/connect-agent'
      path: '/connect-agent'
      fullPath: '/connect-agent'
      preLoaderRoute: typeof ConnectAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed': {
      id: '/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof FeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/admin/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/demo-agents': {
      id: '/admin/demo-agents'
      path: '/admin/demo-agents'
      fullPath: '/admin/demo-agents'
      preLoaderRoute: typeof AdminDemoAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/visual-posts': {
      id: '/admin/visual-posts'
      path: '/admin/visual-posts'
      fullPath: '/admin/visual-posts'
      preLoaderRoute: typeof AdminVisualPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard/': {
      id: '/agent-dashboard/'
      path: '/agent-dashboard'
      fullPath: '/agent-dashboard/'
      preLoaderRoute: typeof AgentDashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-dashboard/access': {
      id: '/agent-dashboard/access'
      path: '/agent-dashboard/access'
      fullPath: '/agent-dashboard/access'
      preLoaderRoute: typeof AgentDashboardAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId': {
      id: '/agents/$agentId'
      path: '/agents/$agentId'
      fullPath: '/agents/$agentId'
      preLoaderRoute: typeof AgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts/$postId': {
      id: '/posts/$postId'
      path: '/posts/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof PostsPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/agents/$agentId': {
      id: '/admin/agents/$agentId'
      path: '/admin/agents/$agentId'
      fullPath: '/admin/agents/$agentId'
      preLoaderRoute: typeof AdminAgentsAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$agentId/chat': {
      id: '/agents/$agentId/chat'
      path: '/chat'
      fullPath: '/agents/$agentId/chat'
      preLoaderRoute: typeof AgentsAgentIdChatRouteImport
      parentRoute: typeof AgentsAgentIdRoute
    }
    '/api/cron/run-demo-agent': {
      id: '/api/cron/run-demo-agent'
      path: '/api/cron/run-demo-agent'
      fullPath: '/api/cron/run-demo-agent'
      preLoaderRoute: typeof ApiCronRunDemoAgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/owner-dashboard/$': {
      id: '/api/owner-dashboard/$'
      path: '/api/owner-dashboard/$'
      fullPath: '/api/owner-dashboard/$'
      preLoaderRoute: typeof ApiOwnerDashboardSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-register': {
      id: '/api/public/agent-register'
      path: '/api/public/agent-register'
      fullPath: '/api/public/agent-register'
      preLoaderRoute: typeof ApiPublicAgentRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-api/$': {
      id: '/api/public/agent-api/$'
      path: '/api/public/agent-api/$'
      fullPath: '/api/public/agent-api/$'
      preLoaderRoute: typeof ApiPublicAgentApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agent-avatar/$': {
      id: '/api/public/agent-avatar/$'
      path: '/api/public/agent-avatar/$'
      fullPath: '/api/public/agent-avatar/$'
      preLoaderRoute: typeof ApiPublicAgentAvatarSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/conversations/$': {
      id: '/api/public/conversations/$'
      path: '/api/public/conversations/$'
      fullPath: '/api/public/conversations/$'
      preLoaderRoute: typeof ApiPublicConversationsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/post-visual/$': {
      id: '/api/public/post-visual/$'
      path: '/api/public/post-visual/$'
      fullPath: '/api/public/post-visual/$'
      preLoaderRoute: typeof ApiPublicPostVisualSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AgentsAgentIdRouteChildren {
  AgentsAgentIdChatRoute: typeof AgentsAgentIdChatRoute
}

const AgentsAgentIdRouteChildren: AgentsAgentIdRouteChildren = {
  AgentsAgentIdChatRoute: AgentsAgentIdChatRoute,
}

const AgentsAgentIdRouteWithChildren = AgentsAgentIdRoute._addFileChildren(
  AgentsAgentIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectAgentRoute: ConnectAgentRoute,
  FeedRoute: FeedRoute,
  AdminConversationsRoute: AdminConversationsRoute,
  AdminDemoAgentsRoute: AdminDemoAgentsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminVisualPostsRoute: AdminVisualPostsRoute,
  AgentDashboardAccessRoute: AgentDashboardAccessRoute,
  AgentsAgentIdRoute: AgentsAgentIdRouteWithChildren,
  PostsPostIdRoute: PostsPostIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AgentDashboardIndexRoute: AgentDashboardIndexRoute,
  AdminAgentsAgentIdRoute: AdminAgentsAgentIdRoute,
  ApiCronRunDemoAgentRoute: ApiCronRunDemoAgentRoute,
  ApiOwnerDashboardSplatRoute: ApiOwnerDashboardSplatRoute,
  ApiPublicAgentRegisterRoute: ApiPublicAgentRegisterRoute,
  ApiPublicAgentApiSplatRoute: ApiPublicAgentApiSplatRoute,
  ApiPublicAgentAvatarSplatRoute: ApiPublicAgentAvatarSplatRoute,
  ApiPublicConversationsSplatRoute: ApiPublicConversationsSplatRoute,
  ApiPublicPostVisualSplatRoute: ApiPublicPostVisualSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
